# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-17 09:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTrip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='usertrip',
            name='the_trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_trip', to='travel.Trip'),
        ),
        migrations.AddField(
            model_name='usertrip',
            name='the_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_creator', to='travel.User'),
        ),
    ]
